### ISSUE TITLE
what is key2id?

### ISSUE THREAD

**Issue by birdhunter22** [FranxYao/dgm_latent_bow#2]
File "main.py", line 91, in main
    config.key_size = len(dset.key2id)
AttributeError: 'Dataset' object has no attribute 'key2id'

how can i resolve this ?

**Comment by FranxYao** [comment]
Oh that is the configuration for the data to text generation task. I think I may forget to switch back to the paraphrase generation setting. Will update before the conference. (Or you could look into https://github.com/tyliupku/wiki2bio for this dataset)

**Comment by birdhunter22** [comment]
ok sure, thank you so much. 
good luck for the conference :))
