### ISSUE TITLE
Question about setting some hyperparameter values

### ISSUE THREAD

**Issue by matejklemen** [FranxYao/dgm_latent_bow#7]
Hi,  
I was wondering whether there is some "intuitive" way to set the following parameters: `max_enc_bow`, `max_dec_bow` and `sample_size`; like how the `max_sent_len` is set to the 95th percentile of training sequence lengths.  
Or are these parameters set based on the validation metric (or is there some additional way)?

**Comment by FranxYao** [comment]
Hi matejklemen, 

max_enc_bow: use the 95% of the bow of all the decoder sentencese. 
For example: for each input sentence, there are 4 references in MSCOCO, so calculate the #bow of the four sentences. Repeat this for all the training instances, and use the 95% of the #bow of for all the training instances. 

sample_size: use 95% of the bow for a single sentence. 

These principles should work for other datasets (this is something I would do). 

Good luck!
